services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: Heki44
      POSTGRES_PASSWORD: password
      PGDATA: /data/burger_restaurant_db
    volumes:
      - db:/data/burger_restaurant_db
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge


volumes:
  db: